/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is normally auto-generated by `next dev` or `next build`.
// It is safe to regenerate — do not edit manually.
